// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeChip_CadastrosOfertas.Database.Context;

namespace WeChip_CadastrosOfertas.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20210424042633_ProdutosMigration")]
    partial class ProdutosMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("WeChip_CadastrosOfertas.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Credito")
                        .HasColumnType("REAL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("WeChip_CadastrosOfertas.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("Preco")
                        .HasColumnType("REAL");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7ca767c-3280-4741-b84e-b526ad245074"),
                            Codigo = "00015",
                            CreatedAt = new DateTime(2021, 4, 24, 4, 26, 32, 944, DateTimeKind.Utc).AddTicks(8803),
                            Descricao = "Mouse",
                            Preco = 20.0,
                            Tipo = "HARDWARE",
                            UpdatedAt = new DateTime(2021, 4, 24, 4, 26, 32, 944, DateTimeKind.Utc).AddTicks(9616)
                        },
                        new
                        {
                            Id = new Guid("78e09f7e-9b29-4973-bc29-85f7c0add936"),
                            Codigo = "00106",
                            CreatedAt = new DateTime(2021, 4, 24, 4, 26, 32, 945, DateTimeKind.Utc).AddTicks(3198),
                            Descricao = "Teclado",
                            Preco = 30.0,
                            Tipo = "HARDWARE",
                            UpdatedAt = new DateTime(2021, 4, 24, 4, 26, 32, 945, DateTimeKind.Utc).AddTicks(3215)
                        },
                        new
                        {
                            Id = new Guid("07b7674e-d493-4e45-9b3e-5edd1ef52fef"),
                            Codigo = "00200",
                            CreatedAt = new DateTime(2021, 4, 24, 4, 26, 32, 945, DateTimeKind.Utc).AddTicks(3271),
                            Descricao = "Monitor 17",
                            Preco = 350.0,
                            Tipo = "HARDWARE",
                            UpdatedAt = new DateTime(2021, 4, 24, 4, 26, 32, 945, DateTimeKind.Utc).AddTicks(3272)
                        },
                        new
                        {
                            Id = new Guid("40d4ea46-03de-47e6-a558-e5e2ce60da6b"),
                            Codigo = "00211",
                            CreatedAt = new DateTime(2021, 4, 24, 4, 26, 32, 945, DateTimeKind.Utc).AddTicks(3275),
                            Descricao = "Pen Drive 8GB",
                            Preco = 30.0,
                            Tipo = "HARDWARE",
                            UpdatedAt = new DateTime(2021, 4, 24, 4, 26, 32, 945, DateTimeKind.Utc).AddTicks(3276)
                        },
                        new
                        {
                            Id = new Guid("a313a41e-b3c3-444a-a480-022b5e1c8635"),
                            Codigo = "00314",
                            CreatedAt = new DateTime(2021, 4, 24, 4, 26, 32, 945, DateTimeKind.Utc).AddTicks(3279),
                            Descricao = "Pen Drive 16GB",
                            Preco = 50.0,
                            Tipo = "HARDWARE",
                            UpdatedAt = new DateTime(2021, 4, 24, 4, 26, 32, 945, DateTimeKind.Utc).AddTicks(3280)
                        },
                        new
                        {
                            Id = new Guid("6360d4f1-4123-48c0-ba53-810b1b3b3673"),
                            Codigo = "00459",
                            CreatedAt = new DateTime(2021, 4, 24, 4, 26, 32, 945, DateTimeKind.Utc).AddTicks(3297),
                            Descricao = "AVAST",
                            Preco = 199.0,
                            Tipo = "SOFTWARE",
                            UpdatedAt = new DateTime(2021, 4, 24, 4, 26, 32, 945, DateTimeKind.Utc).AddTicks(3298)
                        },
                        new
                        {
                            Id = new Guid("6ee8d449-f0a0-4296-a6c5-d66958b84bf9"),
                            Codigo = "01104",
                            CreatedAt = new DateTime(2021, 4, 24, 4, 26, 32, 945, DateTimeKind.Utc).AddTicks(3301),
                            Descricao = "Pacote Office",
                            Preco = 499.0,
                            Tipo = "SOFTWARE",
                            UpdatedAt = new DateTime(2021, 4, 24, 4, 26, 32, 945, DateTimeKind.Utc).AddTicks(3302)
                        },
                        new
                        {
                            Id = new Guid("8774af8f-1b9a-49ea-87e4-05a03ce2b187"),
                            Codigo = "01108",
                            CreatedAt = new DateTime(2021, 4, 24, 4, 26, 32, 945, DateTimeKind.Utc).AddTicks(3305),
                            Descricao = "Spotify (3 meses)",
                            Preco = 45.5,
                            Tipo = "SOFTWARE",
                            UpdatedAt = new DateTime(2021, 4, 24, 4, 26, 32, 945, DateTimeKind.Utc).AddTicks(3306)
                        },
                        new
                        {
                            Id = new Guid("c90e79c4-02df-431e-a5b1-1fc3f15c88f1"),
                            Codigo = "01107",
                            CreatedAt = new DateTime(2021, 4, 24, 4, 26, 32, 945, DateTimeKind.Utc).AddTicks(3308),
                            Descricao = "Netflix (1 mês)",
                            Preco = 199.0,
                            Tipo = "SOFTWARE",
                            UpdatedAt = new DateTime(2021, 4, 24, 4, 26, 32, 945, DateTimeKind.Utc).AddTicks(3309)
                        });
                });

            modelBuilder.Entity("WeChip_CadastrosOfertas.Entities.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContabilizaVenda")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("FinalizaCliente")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Status");
                });

            modelBuilder.Entity("WeChip_CadastrosOfertas.Entities.Status", b =>
                {
                    b.HasOne("WeChip_CadastrosOfertas.Entities.Cliente", "Cliente")
                        .WithMany("Status")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("WeChip_CadastrosOfertas.Entities.Cliente", b =>
                {
                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
